document.write( '<!DOCTYPE html>\n' );
document.write( '<html lang=\"en\">\n' );
document.write( '<head>\n' );
document.write( '    <meta charset=\"UTF-8\">\n' );
document.write( '    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n' );
document.write( '    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n' );
document.write( '    <!-- <title>Document</title> -->\n' );
document.write( '</head>\n' );
document.write( '<body>\n' );
document.write( '    \n' );
document.write( '\n' );
document.write( '\n' );
document.write( '    <footer>\n' );
document.write( '        <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\n' );
document.write( '        <!-- <a href=\"https://www.facebook.com/SamyaSaha08\" target=\"_blank\" class=\"fa fa-facebook\"></a>\n' );
document.write( '        <a href=\"https://www.twitter.com/SamyaSaha08\" target=\"_blank\" class=\"fa fa-twitter\"></a>\n' );
document.write( '        <a href=\"https://bit.ly/SamyaSahaYt\" target=\"_blank\" class=\"fa fa-youtube\"></a>\n' );
document.write( '        <a href=\"https://www.instagram.com/SamyaSaha08\" target=\"_blank\" class=\"fa fa-instagram\"></a><br> -->\n' );
document.write( '        Copyright © 2020-22 <b><i>Samya Saha</i></b><br>- All Rights Reserved.<br><br>\n' );
document.write( '        <h6>Source code available on Github: <a href=\"https://github.com/Samya-S/jee-challenger---html\" target=\"_blank\" style=\"text-decoration: none; isolation: unset;\">Click here</a></h6>\n' );
document.write( '        <br>\n' );
document.write( '        <div>\n' );
document.write( '          <h3 style=\"font-weight: normal; font-family: monospace;\"><p id=\"date&time\"></p></h3>\n' );
document.write( '          <script src=\"https://jeechallenger.netlify.app/common/date-time.js\"></script>\n' );
document.write( '        </div>\n' );
document.write( '    </footer>\n' );
document.write( '\n' );
document.write( '\n' );
document.write( '\n' );
document.write( '    <style>\n' );
document.write( '        footer {\n' );
document.write( '          text-align: center;\n' );
document.write( '          bottom: 0;\n' );
document.write( '          left: 0;\n' );
document.write( '          right: 0;\n' );
document.write( '          padding: 4%;\n' );
document.write( '          background-color: rgba(212, 212, 212, 0.26);\n' );
document.write( '        }\n' );
document.write( '\n' );
document.write( '        /*social-media-buttons*/\n' );
document.write( '        .fa {\n' );
document.write( '            padding: 7px; \n' );
document.write( '            border-radius: 50%; \n' );
document.write( '            width: 17px; \n' );
document.write( '            font-size: 15px; \n' );
document.write( '            text-align: center; \n' );
document.write( '            text-decoration: none; \n' );
document.write( '            margin: 5px 2px; \n' );
document.write( '            isolation: isolate;\n' );
document.write( '        }\n' );
document.write( '\n' );
document.write( '        /* .fa:hover {opacity: 0.7;} */\n' );
document.write( '        .fa-facebook {background: #3b5998;color: white;}\n' );
document.write( '        .fa-facebook:hover {opacity: 0.7;}\n' );
document.write( '        .fa-twitter {background: #55acee;color: white;}\n' );
document.write( '        .fa-twitter:hover {opacity: 0.7;}\n' );
document.write( '        .fa-youtube {background: #bb0000;color: white;}\n' );
document.write( '        .fa-youtube:hover {opacity: 0.7;}\n' );
document.write( '        .fa-instagram {background: #c00271;color: white;}  \n' );
document.write( '        .fa-instagram:hover {opacity: 0.7;}\n' );
document.write( '    </style>\n' );
document.write( '\n' );
document.write( '\n' );
document.write( '\n' );
document.write( '\n' );
document.write( '\n' );
document.write( '\n' );
document.write( '    <!-- temporary message to inform about change in domain  -->\n' );
document.write( '    <div class=\"alert\" id=\"alertID\">\n' );
document.write( '      <span class=\"closebtn fa fa-times\"></span> \n' );
document.write( '      <!-- <strong>Attention!</strong>  -->\n' );
document.write( '      We have moved our site to <a href=\"https://jeechallenger.herokuapp.com/\" style=\"text-decoration: none; color: yellow;\">jeechallenger.herokuapp.com/</a>. Please bookmark the new site. Thank you!\n' );
document.write( '    </div>\n' );
document.write( '\n' );
document.write( '    <script>\n' );
document.write( '        var close = document.getElementsByClassName(\"closebtn\");\n' );
document.write( '        var i;\n' );
document.write( '\n' );
document.write( '        for (i = 0; i < close.length; i++) {\n' );
document.write( '            close[i].onclick = function(){\n' );
document.write( '                var div = this.parentElement;\n' );
document.write( '                div.style.opacity = \"0\";\n' );
document.write( '                setTimeout(function(){ div.style.display = \"none\"; }, 500);\n' );
document.write( '            }\n' );
document.write( '        }\n' );
document.write( '\n' );
document.write( '\n' );
document.write( '\n' );
document.write( '        var alertM = document.getElementById(\"alertID\");\n' );
document.write( '\n' );
document.write( '\n' );
document.write( '        // display alert once in a session\n' );
document.write( '        // if(sessionStorage.getItem(\'showAlert\') != \"false\"){          //  hidden\n' );
document.write( '        //   alertM.style.display = \"block\";  \n' );
document.write( '        //   sessionStorage.setItem(\'showAlert\', \"false\");\n' );
document.write( '        // }\n' );
document.write( '    </script>\n' );
document.write( '\n' );
document.write( '    <style>\n' );
document.write( '        .alert {\n' );
document.write( '          display: none;\n' );
document.write( '          padding: 20px;\n' );
document.write( '          background-color: #f44336;\n' );
document.write( '          color: white;\n' );
document.write( '          position: fixed;\n' );
document.write( '          bottom: 0px;\n' );
document.write( '          right: 0px;\n' );
document.write( '          left: 0px;\n' );
document.write( '          /* width: 100%; */\n' );
document.write( '          z-index: 1000;\n' );
document.write( '          opacity: 1;\n' );
document.write( '          transition: opacity 0.5s;\n' );
document.write( '        }\n' );
document.write( '\n' );
document.write( '        .closebtn {\n' );
document.write( '          position: fixed;\n' );
document.write( '          /* margin-left: 15px; */\n' );
document.write( '          color: white;\n' );
document.write( '          /* font-weight: bold; */\n' );
document.write( '          float: right;\n' );
document.write( '          right: 10px;\n' );
document.write( '          font-size: 22px;\n' );
document.write( '          line-height: 0px;\n' );
document.write( '          cursor: pointer;\n' );
document.write( '          transition: 0.3s;\n' );
document.write( '        }\n' );
document.write( '\n' );
document.write( '        .closebtn:hover {\n' );
document.write( '          color: black;\n' );
document.write( '        }\n' );
document.write( '    </style>\n' );
document.write( '\n' );
document.write( '\n' );
document.write( '\n' );
document.write( '    <?php ?>\n' );
document.write( '\n' );
document.write( '\n' );
document.write( '</body>\n' );
document.write( '</html>' );
