document.write( '<!DOCTYPE html>\n' );
document.write( '<html lang=\"en\">\n' );
document.write( '<head>\n' );
document.write( '    <meta charset=\"UTF-8\">\n' );
document.write( '    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n' );
document.write( '    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n' );
document.write( '    <!-- <title>Document</title> -->\n' );
document.write( '</head>\n' );
document.write( '<body>\n' );
document.write( '    \n' );
document.write( '\n' );
document.write( '\n' );
document.write( '        <header id=\"navbar\">\n' );
document.write( '          <div class=\"menu-toggle\">\n' );
document.write( '            <button class=\"NavOpenButton\" onclick=\"toggleNavOpen()\"><i class=\"fa fa-bars NavOpenButton\" aria-hidden=\"true\"></i></button>\n' );
document.write( '          </div>\n' );
document.write( '          <p>\n' );
document.write( '            <a href=\"../home\">\n' );
document.write( '              <b>JEE Challenger</b>\n' );
document.write( '            </a>\n' );
document.write( '          </p>\n' );
document.write( '          <nav>\n' );
document.write( '            <div class=\"menu-toggle\">\n' );
document.write( '              <button class=\"NavCloseButton\" onclick=\"toggleNavClose()\">×</button>\n' );
document.write( '            </div>\n' );
document.write( '            <ul class=\"ul-class\">\n' );
document.write( '              <li><a href=\"../home\" id=\"navBtn_Home\"><b>Home</b></a></li>\n' );
document.write( '              <li>\n' );
document.write( '                <div class=\"dropdown\">\n' );
document.write( '                  <button class=\"dropbtn\" id=\"navBtn_Materials\">Materials<i class=\"rotate fa fa-caret-down\"></i></button>\n' );
document.write( '                  <ul>\n' );
document.write( '                    <div class=\"dropdown-content\">\n' );
document.write( '                      <li><a id=\"navBtn_Phy\" href=\"../materials/physics\">Physics PDFs</a></li>\n' );
document.write( '                      <li><a id=\"navBtn_Chem\" href=\"../materials/chemistry\">Chemistry PDFs</a></li>\n' );
document.write( '                      <li><a id=\"navBtn_Maths\" href=\"../materials/mathematics\">Mathematics PDFs</a></li>\n' );
document.write( '                      <li><a id=\"navBtn_PYQs\" href=\"../materials/chapterwise-solved-pyqs\">Chapterwise solved PYQs</a></li>\n' );
document.write( '                      <li><a id=\"navBtn_More\" href=\"../materials/more-study-materials\">More study materials</a></li>\n' );
document.write( '                    </div>\n' );
document.write( '                  </ul>\n' );
document.write( '                </div>\n' );
document.write( '              </li>\n' );
document.write( '              <li>\n' );
document.write( '                <div class=\"dropdown\">\n' );
document.write( '                  <button class=\"dropbtn\" id=\"navBtn_OfficialLinks\">Officials links<i class=\"rotate fa fa-caret-down\"></i></button>\n' );
document.write( '                  <ul>\n' );
document.write( '                    <div class=\"dropdown-content\">\n' );
document.write( '                      <li><a id=\"navBtn_Main\" href=\"../official-links/jee-main\">JEE Main</a></li>\n' );
document.write( '                      <li><a id=\"navBtn_Adv\" href=\"../official-links/jee-advanced\">JEE Advanced</a></li>                \n' );
document.write( '                    </div>\n' );
document.write( '                  </ul>\n' );
document.write( '                </div>\n' );
document.write( '              </li>\n' );
document.write( '              <li>\n' );
document.write( '                <div class=\"dropdown\">\n' );
document.write( '                  <button class=\"dropbtn\" id=\"navBtn_MorePlatforms\">More platforms<i class=\"rotate fa fa-caret-down\"></i></button>\n' );
document.write( '                  <ul>\n' );
document.write( '                    <div class=\"dropdown-content\">\n' );
document.write( '                      <li><a id=\"navBtn_Unacademy\" href=\"../more-platforms/unacademy\">Unacademy</a></li>\n' );
document.write( '                      <li><a id=\"navBtn_ApniKaksha\" href=\"../more-platforms/apnikaksha\">Apni Kaksha</a></li>\n' );
document.write( '                      <li><a id=\"navBtn_PW\" href=\"../more-platforms/physicswallah\">Physics Wallah</a></li>\n' );
document.write( '                    </div>\n' );
document.write( '                  </ul>\n' );
document.write( '                </div>\n' );
document.write( '              </li>\n' );
document.write( '            </ul>\n' );
document.write( '          </nav>\n' );
document.write( '          \n' );
document.write( '    \n' );
document.write( '        </header>\n' );
document.write( '\n' );
document.write( '\n' );
document.write( '</body>\n' );
document.write( '</html>' );