document.write( '<!DOCTYPE html>\n' );
document.write( '<html lang=\"en\">\n' );
document.write( '<head>\n' );
document.write( '    <meta charset=\"UTF-8\">\n' );
document.write( '    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n' );
document.write( '    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n' );
document.write( '    <!-- <title>Document</title> -->\n' );
document.write( '</head>\n' );
document.write( '<body>\n' );
document.write( '    \n' );
document.write( '\n' );
document.write( '\n' );
document.write( '    <a href=\"https://t.me/+oOnj4y_ZYqYyZjA1\" target=\"_blank\" class=\"telegram-float\">\n' );
document.write( '        <p>Join us on</p>\n' );
document.write( '        <i class=\"fa fa-telegram\"></i>\n' );
document.write( '    </a>\n' );
document.write( '\n' );
document.write( '\n' );
document.write( '\n' );
document.write( '    <style>        \n' );
document.write( '        .telegram-float{\n' );
document.write( '            position:fixed;\n' );
document.write( '            z-index: 5;\n' );
document.write( '            width:50px;\n' );
document.write( '            height:fit-content;\n' );
document.write( '            top: 50%;\n' );
document.write( '            transform: translate(0, -50%);\n' );
document.write( '            left:0px;\n' );
document.write( '            background-color:rgb(255, 255, 255);\n' );
document.write( '            color:#2e87ca;\n' );
document.write( '            border-radius:15px;\n' );
document.write( '            border-top-left-radius: 0px;\n' );
document.write( '            border-bottom-left-radius: 0px;\n' );
document.write( '            text-align:center;\n' );
document.write( '            text-decoration: none;\n' );
document.write( '            padding: 5px;\n' );
document.write( '            box-shadow: 2px 2px 3px #999;\n' );
document.write( '        }\n' );
document.write( '        .telegram-float i{\n' );
document.write( '            transform: translate(-11px, 0px);\n' );
document.write( '            /* margin: 0; */\n' );
document.write( '            padding: 0;\n' );
document.write( '            font-size: 40px;\n' );
document.write( '        }\n' );
document.write( '        .telegram-float p{\n' );
document.write( '            font-size: 20px;\n' );
document.write( '            margin: 0;\n' );
document.write( '        }\n' );
document.write( '    </style>\n' );
document.write( '\n' );
document.write( '\n' );
document.write( '\n' );
document.write( '\n' );
document.write( '</body>\n' );
document.write( '</html>' );